# OCI Email Delivery module.
#
# Grav doesn't send transactional mail itself — this stays available for
# anything on the domain that needs outbound SMTP, and for future
# member-email/notification use cases.
#
# What this creates:
#   1. An approved sender address for the domain (required before OCI will
#      relay any mail from it)
#   2. A DKIM key for the domain, so receiving mail servers can verify mail
#      actually came from this domain (the DNS module consumes this
#      resource's outputs to add the DKIM TXT record)
#   3. A dedicated IAM user scoped to nothing but SMTP sending, plus its
#      SMTP credential (OCI Email Delivery auth is IAM-user-based, not a
#      per-domain secret)
#   4. The OCI-generated SMTP credential stored in the existing Vault

resource "oci_email_sender" "this" {
  compartment_id = var.compartment_ocid
  email_address  = var.sender_email_address

  freeform_tags = merge(var.freeform_tags, {
    Service = "email-delivery"
  })
}

resource "oci_email_dkim" "this" {
  # No compartment_id here — OCI derives it from email_domain_id and rejects
  # it if set explicitly (this is a "computed, not configurable" attribute
  # on this resource, unlike oci_email_sender/oci_email_email_domain which
  # both do take one).
  name            = "dkim-${replace(var.domain_name, ".", "-")}"
  email_domain_id = oci_email_email_domain.this.id

  freeform_tags = merge(var.freeform_tags, {
    Service = "email-delivery"
  })
}

resource "oci_email_email_domain" "this" {
  compartment_id = var.compartment_ocid
  name           = var.domain_name

  freeform_tags = merge(var.freeform_tags, {
    Service = "email-delivery"
  })
}

# -----------------------------------------------------------------------------
# Dedicated IAM user for SMTP sending only
# -----------------------------------------------------------------------------
# Scoped narrowly on purpose: this user exists to hold an SMTP credential and
# nothing else. It is not added to any group with console or API access —
# write the matching IAM policy statement by hand (kept manual since identity
# resources are typically managed outside a project's own Terraform root).

resource "oci_identity_user" "smtp_sender" {
  compartment_id = var.tenancy_ocid
  name           = var.smtp_user_name
  description    = "SMTP-only service user for OCI Email Delivery (${var.domain_name}). No console/API access — SMTP credential only."

  freeform_tags = merge(var.freeform_tags, {
    Service = "email-delivery"
    Purpose = "smtp-sender"
  })
}

resource "oci_identity_smtp_credential" "this" {
  user_id     = oci_identity_user.smtp_sender.id
  description = "SMTP credential for ${var.domain_name} outbound mail"
}

# -----------------------------------------------------------------------------
# Store the OCI-generated SMTP credential in the existing Vault
# -----------------------------------------------------------------------------
# The SMTP password is generated by OCI itself (returned once, on credential
# creation) — this resource just stores that real value, it doesn't generate
# one.

resource "oci_vault_secret" "smtp_credential" {
  compartment_id = var.compartment_ocid
  vault_id       = var.vault_ocid
  key_id         = var.key_ocid
  secret_name    = "secret-email-delivery-${replace(var.domain_name, ".", "-")}-smtp"
  description    = "OCI Email Delivery SMTP credential for ${var.domain_name}. Username: ${oci_identity_smtp_credential.this.username}"

  secret_content {
    content_type = "BASE64"
    content      = base64encode(oci_identity_smtp_credential.this.password)
    name         = "initial"
    stage        = "CURRENT"
  }

  freeform_tags = merge(var.freeform_tags, {
    ManagedBy = "terraform"
    Role      = "smtp-credential"
  })

  lifecycle {
    # SMTP credential passwords are shown only once at creation and cannot
    # be retrieved again from OCI — never let a later apply overwrite this
    # with something else. Rotation means creating a new
    # oci_identity_smtp_credential and a new secret version by hand.
    ignore_changes = [secret_content]
  }
}

# -----------------------------------------------------------------------------
# Store the SMTP username alongside the password
# -----------------------------------------------------------------------------
# The username itself isn't secret (it's the IAM user's OCID-based login
# string, visible via the smtp_username output too), but storing it next to
# the password means one lookup gets you the full credential pair instead of
# combining a Vault read with a separate `terraform output`.

resource "oci_vault_secret" "smtp_username" {
  compartment_id = var.compartment_ocid
  vault_id       = var.vault_ocid
  key_id         = var.key_ocid
  secret_name    = "secret-email-delivery-${replace(var.domain_name, ".", "-")}-smtp-username"
  description    = "OCI Email Delivery SMTP username for ${var.domain_name} (pairs with the -smtp secret's password)."

  secret_content {
    content_type = "BASE64"
    content      = base64encode(oci_identity_smtp_credential.this.username)
    name         = "initial"
    stage        = "CURRENT"
  }

  freeform_tags = merge(var.freeform_tags, {
    ManagedBy = "terraform"
    Role      = "smtp-username"
  })
}
